package org.hccp.elses;

public enum TokenType {
    //SINGLE-CHAR TOKENS
    INCREMENT_ANGLE, FORWARD, PEN_UP_FORWARD, RIGHT_TURN, LEFT_TURN,
    POP, PUSH, REVERSE, DOT, OPEN_POLYGON, CLOSE_POLYGON, COLON, NEWLINE, SEMICOLON, EQUALS,

    // ONE OR TWO CHARACTER TOKENS
    THEN,DECREMENT_ANGLE,

    // LITERALS
    IDENTIFIER, STRING, NUMBER,

    //KEYWORDS
    AXIOM, ANGLE,

    EOF
}
